
const comics=window.COMICS||[],$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const state=JSON.parse(localStorage.getItem('dv-v4')||'{"favorites":[],"wishlist":[],"snapshots":[],"corrections":{}}');
const save=()=>localStorage.setItem('dv-v4',JSON.stringify(state));
const effective=c=>({...c,...(state.corrections[c.id]||{})});
const all=()=>comics.map(effective);
const rawTotal=()=>all().reduce((s,c)=>s+c.rawMid,0);
function card(base){const c=effective(base),fav=state.favorites.includes(c.id),issue=c.issue==='Issue to verify'?'<span class="pending">Issue to verify</span>':c.issue;return `<article class="card" data-id="${c.id}"><div class="cover"><img src="${c.image}" loading="lazy" alt="${c.title} ${c.issue}"><span class="tag">Photo ${String(c.id).padStart(3,'0')}</span><button class="heart ${fav?'on':''}" data-fav="${c.id}">♥</button></div><div class="body"><h3>${c.title} ${issue}</h3><div class="meta">${c.publisher} • ${c.genre} • ${c.box}</div><div class="storyPreview">${c.summary}</div><div class="badges">${c.keyEvents.slice(0,2).map(b=>`<span class="badge key">${b}</span>`).join('')}<span class="badge">Demand ${c.demand}/100</span></div>${c.high?`<div class="values"><div class="value"><small>Raw</small><b>${money(c.low)}–${money(c.high)}</b></div><div class="value"><small>CGC 9.8*</small><b>${money(c.cgc98Low)}–${money(c.cgc98High)}</b></div></div>`:'<div class="meta">Value pending verification</div>'}</div></article>`}
function init(){const list=all(),verified=list.filter(c=>c.issue!=='Issue to verify').length,priced=list.filter(c=>c.high).length;$('#stats').innerHTML=[[list.length,'Actual cover photos'],[verified,'Issue numbers confirmed'],[priced,'Books with value estimates'],[money(rawTotal()),'Estimated raw midpoint']].map(x=>`<div class="stat"><b>${x[0]}</b><small>${x[1]}</small></div>`).join('');const opts=(id,vals)=>vals.forEach(v=>$(id).insertAdjacentHTML('beforeend',`<option>${v}</option>`));opts('#publisher',[...new Set(list.map(c=>c.publisher))].sort());opts('#genre',[...new Set(list.map(c=>c.genre))].sort());render();dashboard();top25();saved();renderCharacters();renderVerify();snapshot(false);$('#verifiedBox').textContent=`${verified} issue numbers confirmed`;}
function render(){let q=$('#search').value.toLowerCase(),p=$('#publisher').value,g=$('#genre').value,s=$('#sort').value;let list=all().filter(c=>[c.title,c.issue,c.publisher,c.genre,c.summary,...c.keyEvents,...c.characters].join(' ').toLowerCase().includes(q)&&(!p||c.publisher===p)&&(!g||c.genre===g));list.sort((a,b)=>s==='value'?b.rawMid-a.rawMid:s==='demand'?b.demand-a.demand:s==='file'?a.id-b.id:`${a.title}${a.issue}`.localeCompare(`${b.title}${b.issue}`));$('#grid').innerHTML=list.map(card).join('')}
function dashboard(){const list=all(),counts={};list.forEach(c=>counts[c.publisher]=(counts[c.publisher]||0)+1);const rows=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8),max=rows[0]?.[1]||1;$('#pubBars').innerHTML=rows.map(([n,v])=>`<div class="barrow"><div class="barlabel"><span>${n}</span><b>${v}</b></div><div class="bar" style="--w:${v/max*100}%"><i></i></div></div>`).join('');const v=list.filter(c=>c.issue!=='Issue to verify').length;$('#status').innerHTML=`<div class="barlabel"><span>Photographed</span><b>94 / 94</b></div><div class="bar" style="--w:100%"><i></i></div><div class="barlabel" style="margin-top:14px"><span>Issue number verified</span><b>${v} / 94</b></div><div class="bar" style="--w:${v/94*100}%"><i></i></div>`;drawChart()}
function snapshot(manual=true){const date=new Date().toISOString().slice(0,10),last=state.snapshots.at(-1);if(!last||last.date!==date||manual){state.snapshots.push({date,value:rawTotal()});state.snapshots=state.snapshots.slice(-24);save()}drawChart()}
function drawChart(){const c=$('#chart'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||700,h=230;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const pts=state.snapshots.length?state.snapshots:[{date:'Now',value:rawTotal()}],vals=pts.map(p=>p.value),min=Math.min(...vals)*.9,max=Math.max(...vals)*1.1||1;ctx.strokeStyle='#2b3d5e';for(let i=0;i<5;i++){let y=20+i*(h-40)/4;ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(w-10,y);ctx.stroke()}ctx.strokeStyle='#55d7a4';ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>{let x=40+(pts.length===1?0:i/(pts.length-1)*(w-60)),y=20+(max-p.value)/(max-min||1)*(h-40);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#f3c65c';ctx.font='12px system-ui';ctx.fillText('Estimated raw midpoint',42,17)}
function top25(){const list=all().filter(c=>c.high).sort((a,b)=>b.rawMid-a.rawMid).slice(0,25);$('#ranking').innerHTML=list.map((c,i)=>`<div class="rank"><div class="ranknum">${i+1}</div><img src="${c.image}"><div><b>${c.title} ${c.issue}</b><div class="meta">${c.publisher} • ${c.keyEvents.slice(0,2).join(', ')}</div></div><div class="rankvalue">${money(c.rawMid)}</div></div>`).join('')}
function renderCharacters(){const chars=[...new Set(all().flatMap(c=>c.characters))].sort();$('#characterChips').innerHTML=chars.map(ch=>`<button class="characterChip" data-character="${ch}">${ch}</button>`).join('');$('#characterResults').innerHTML=all().slice(0,12).map(card).join('')}
function renderVerify(){const list=all().filter(c=>c.issue==='Issue to verify'||state.corrections[c.id]);$('#verifyList').innerHTML=list.map(c=>`<div class="verifyRow" data-verify="${c.id}"><img src="${c.image}"><div><b>${c.title}</b><div class="meta">Photo ${String(c.id).padStart(3,'0')}</div></div><input data-field="issue" value="${c.issue}" aria-label="Issue number"><textarea data-field="summary" aria-label="Issue summary">${c.summary}</textarea><button data-saveverify="${c.id}">Save</button></div>`).join('')||'<p>All issue numbers have been verified.</p>'}
function saved(){const mini=c=>`<div class="mini" data-id="${c.id}"><img src="${c.image}"><div>${c.title} ${c.issue}</div></div>`;const list=all();$('#favorites').innerHTML=list.filter(c=>state.favorites.includes(c.id)).map(mini).join('')||'<p>No favorites yet.</p>';$('#wishlist').innerHTML=list.filter(c=>state.wishlist.includes(c.id)).map(mini).join('')||'<p>No wishlist items yet.</p>'}
function detail(id){const c=effective(comics.find(x=>x.id==id));$('#detail').innerHTML=`<div class="detail"><img src="${c.image}"><div class="detailText"><h1>${c.title} ${c.issue}</h1><p class="meta">${c.publisher} • ${c.genre} • Photo ${String(c.id).padStart(3,'0')}</p><h3>Issue summary</h3><p>${c.summary}</p><h3>Key events</h3><ul>${c.keyEvents.map(e=>`<li>${e}</li>`).join('')||'<li>No major key event currently recorded.</li>'}</ul><h3>Key characters</h3><div class="charactersList">${c.characters.map(ch=>`<span class="characterBadge">${ch}</span>`).join('')}</div>${c.high?`<h3>Raw: ${money(c.low)}–${money(c.high)}</h3><h3>Provisional CGC 9.8*: ${money(c.cgc98Low)}–${money(c.cgc98High)}</h3>`:'<h3>Value pending verification</h3>'}<p class="meta">*Planning estimate, not a certified appraisal.</p><div class="actions"><button data-mf="${c.id}">${state.favorites.includes(c.id)?'Remove favorite':'Add favorite'}</button><button data-mw="${c.id}">${state.wishlist.includes(c.id)?'Remove wishlist':'Add wishlist'}</button></div></div></div>`;$('#modal').classList.add('open')}
function exportCorrections(){const blob=new Blob([JSON.stringify(state.corrections,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='davids-comic-vault-corrections.json';a.click();URL.revokeObjectURL(a.href)}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){$$('nav button').forEach(b=>b.classList.remove('active'));nav.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+nav.dataset.view).classList.add('active');$('nav').classList.remove('open')}const fav=e.target.closest('[data-fav]');if(fav){e.stopPropagation();let id=+fav.dataset.fav;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render();saved()}const c=e.target.closest('.card');if(c&&!fav)detail(+c.dataset.id);const m=e.target.closest('.mini');if(m)detail(+m.dataset.id);const ch=e.target.closest('[data-character]');if(ch){$$('.characterChip').forEach(x=>x.classList.remove('active'));ch.classList.add('active');$('#characterResults').innerHTML=all().filter(c=>c.characters.includes(ch.dataset.character)).map(card).join('')}if(e.target.dataset.saveverify){const row=e.target.closest('[data-verify]'),id=+e.target.dataset.saveverify,issue=row.querySelector('[data-field="issue"]').value.trim(),summary=row.querySelector('[data-field="summary"]').value.trim();state.corrections[id]={...(state.corrections[id]||{}),issue,summary};save();render();renderVerify();dashboard();$('#verifiedBox').textContent=`${all().filter(c=>c.issue!=='Issue to verify').length} issue numbers confirmed`;}if(e.target.dataset.mf){let id=+e.target.dataset.mf;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();detail(id);render();saved()}if(e.target.dataset.mw){let id=+e.target.dataset.mw;state.wishlist=state.wishlist.includes(id)?state.wishlist.filter(x=>x!==id):[...state.wishlist,id];save();detail(id);saved()}});
$('#close').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.remove('open')};$('#menu').onclick=()=>$('nav').classList.toggle('open');$('#snapshot').onclick=()=>snapshot(true);$('#exportCorrections').onclick=exportCorrections;['search','publisher','genre','sort'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));document.addEventListener('DOMContentLoaded',init);
